# Generated by Django 5.1.3 on 2024-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beejournal', '0002_alter_historicalqueen_color_alter_queen_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspection',
            name='queen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='queen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='larva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalqueen',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='larva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queen',
            name='date',
            field=models.DateField(),
        ),
    ]
