# Generated by Django 5.1.3 on 2024-12-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beejournal', '0003_historicalinspection_queen_inspection_queen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinspection',
            name='mood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalinspection',
            name='varroa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='mood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='varroa',
            field=models.IntegerField(default=0),
        ),
    ]
