# Generated by Django 5.1.3 on 2024-12-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beejournal', '0004_alter_historicalinspection_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhive',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hive',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
