# Generated by Django 5.1.3 on 2024-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beejournal', '0006_historicalvarroa_varroa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalqueen',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'Hvid (1-6)'), ('yellow', 'Gul (2-7)'), ('red', 'Rød (3-8)'), ('green', 'Grøn (4-9)'), ('blue', 'Blå (5-0)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='queen',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'Hvid (1-6)'), ('yellow', 'Gul (2-7)'), ('red', 'Rød (3-8)'), ('green', 'Grøn (4-9)'), ('blue', 'Blå (5-0)')], max_length=8, null=True),
        ),
    ]
